file_format: "1"
id: corne
name: Corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [nice!nano]
exposes: []
features:
  - keys
  - display
  - underglow
siblings:
  - corne_left
  - corne_right